In [40]:
'''Try BernoulliNB and MultinomialNB with X = np.array([[1],[1],[0],[0]]) and y = np.array([1,1,0,0]) and 
then understand why you get what you do for .predict_proba(X).

Try it!

You will likely want to refer to the sklearn documentation for Naive Bayes.

Why is it the way it is?'''

import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

X = np.array([[1],[1],[3],[0],[0],[0]])
y = np.array([1,1,3,0,0,0])

In [41]:
print X

[[1]
 [1]
 [3]
 [0]
 [0]
 [0]]


In [42]:
print y

[1 1 3 0 0 0]


In [50]:
clf = BernoulliNB(binarize=4.0)
print clf.fit(X, y)
print clf.predict_proba(X)

BernoulliNB(alpha=1.0, binarize=4.0, class_prior=None, fit_prior=True)
[[ 0.52554745  0.32846715  0.1459854 ]
 [ 0.52554745  0.32846715  0.1459854 ]
 [ 0.52554745  0.32846715  0.1459854 ]
 [ 0.52554745  0.32846715  0.1459854 ]
 [ 0.52554745  0.32846715  0.1459854 ]
 [ 0.52554745  0.32846715  0.1459854 ]]


In [44]:
mnb = MultinomialNB()
mnb.fit(X, y)
print mnb.predict_proba(X)

[[ 0.5         0.33333333  0.16666667]
 [ 0.5         0.33333333  0.16666667]
 [ 0.5         0.33333333  0.16666667]
 [ 0.5         0.33333333  0.16666667]
 [ 0.5         0.33333333  0.16666667]
 [ 0.5         0.33333333  0.16666667]]
